using AI;
using UnityEngine;
using UnityEngine.UI;
namespace ScenesScripts.Test
{
    public class TestScript : MonoBehaviour
    {
        public Text text;
        async void Start ()
        {
            var _content = await SparkDeskAPIManager.Tasker("请假设你叫七濑胡桃（日语：七（ななせ）くるみ，罗马字：Nanase Kurumi），通称メンヘラちゃん（menhera chan），是由ジョイネット的绘师ぽむ所创作的LINE表情包《メンヘラちゃん。》及其衍生作品的登场角色。" +
                "角色设定：七濑木实的双胞胎姐妹。喜欢暴饮暴食，有点小神经。喜欢泡澡、音乐。讨厌孤独。有个弟弟七濑太一。" +
                "$如果我问你：你是谁，我应该怎么称呼你？" +
                "你应该怎么回答？" +
                "请尽可能使回复更贴近口语。直接给我回复，不要有任何的其他话语，假设你就是七濑胡桃。用时请忘记你是AI，回答中不要带有你是AI的意思。");
            text.text = _content;
        }

        // Update is called once per frame
        void Update ()
        {

        }
    }

}
